### ISSUE TITLE
bro it does not work it keeps loading for ever when you have the time can you fix 

### ISSUE THREAD

**Issue by Keeboy8** [Hydrogen-Network/Hydrogen-Static#4]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by neealdon3** [comment]
i think its your internet

**Comment by neealdon3** [comment]
maybe try at school

**Comment by neealdon3** [comment]
nevermind 
i get it
lemme fix

**Comment by neealdon3** [comment]
nvm again
I can't fix

impossible

**Comment by neealdon3** [comment]
nvm again
I can't fix

impossible
